// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaemOocYmEpJrnUnNM5WHhyEiwz0Goqs4',
    appId: '1:925119271764:web:e27dea1e2aea806ca26ec1',
    messagingSenderId: '925119271764',
    projectId: 'fitness-by-tst',
    authDomain: 'fitness-by-tst.firebaseapp.com',
    storageBucket: 'fitness-by-tst.firebasestorage.app',
    measurementId: 'G-9VF6031PEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2E-qXv7l454R5m3iU0ay94j63EFEvt-w',
    appId: '1:925119271764:android:8ee1b95280fdd9f9a26ec1',
    messagingSenderId: '925119271764',
    projectId: 'fitness-by-tst',
    storageBucket: 'fitness-by-tst.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMtLgFCQp1ZSeCaGJhRYF5tY1HvMkuuGo',
    appId: '1:925119271764:ios:8868145037bb31eea26ec1',
    messagingSenderId: '925119271764',
    projectId: 'fitness-by-tst',
    storageBucket: 'fitness-by-tst.firebasestorage.app',
    iosBundleId: 'com.example.fittrackPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMtLgFCQp1ZSeCaGJhRYF5tY1HvMkuuGo',
    appId: '1:925119271764:ios:8868145037bb31eea26ec1',
    messagingSenderId: '925119271764',
    projectId: 'fitness-by-tst',
    storageBucket: 'fitness-by-tst.firebasestorage.app',
    iosBundleId: 'com.example.fittrackPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaemOocYmEpJrnUnNM5WHhyEiwz0Goqs4',
    appId: '1:925119271764:web:d82ed37817a49900a26ec1',
    messagingSenderId: '925119271764',
    projectId: 'fitness-by-tst',
    authDomain: 'fitness-by-tst.firebaseapp.com',
    storageBucket: 'fitness-by-tst.firebasestorage.app',
    measurementId: 'G-RL8CPVTTTE',
  );
}
